JN.Web/Areas/APP/Controllers/CashTransferController.cs
using JN.Data.Extensions;
using JN.Data.Service;
using JN.Services.CustomException;
using JN.Services.Manager;
using JN.Services.Tool;
using MvcCore.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace JN.Web.Areas.APP.Controllers
{
    public class CashTransferController : BaseController
    {
        object obj = new object();
        private static List<Data.SysParam> cacheSysParam = null; 
        private readonly IUserService UserService;
        private readonly ITakeCashService TakeCashService;
        private readonly IRaCoinService RaCoinService;
        private readonly ITransferService TransferService;
        private readonly ISysDBTool SysDBTool;
        private readonly IActLogService ActLogService;
        private readonly IWalletLogService WalletLogService;
        private readonly ICurrencyService CurrencyService;
        public CashTransferController(ISysDBTool SysDBTool,
            IUserService UserService,
            ITakeCashService TakeCashService,
            IRaCoinService RaCoinService,
            ITransferService TransferService,
            IActLogService ActLogService,
            IWalletLogService WalletLogService,
            ICurrencyService CurrencyService
            )
        {
            this.UserService = UserService;
            this.TakeCashService = TakeCashService;
            this.RaCoinService = RaCoinService;
            this.TransferService = TransferService;
            this.SysDBTool = SysDBTool;
            this.ActLogService = ActLogService;
            this.WalletLogService = WalletLogService;
            this.CurrencyService = CurrencyService;
            cacheSysParam = MvcCore.Unity.Get<JN.Data.Service.ISysParamService>().ListCache("sysparams", x => x.ID < 8000).ToList();

        }

        #region 币种转出提币和列表

        /// <summary>
        /// 币种转出提币
        /// </summary>
        /// <param name="number"></param>
        /// <returns></returns>
        public ActionResult CurTransferOut(int? page)
        {
            var c = CurrencyService.List(x => x.LineSwitch && !(x.IsCashCurrency ?? false)).Count()==0 ? new JN.Data.Currency { ID = 0 } : CurrencyService.List(x => x.LineSwitch && !(x.IsCashCurrency ?? false)).OrderBy(x => x.ID).FirstOrDefault();//获取最后一条

            if (c.ID == 0) return Redirect("/home/index");
            int curid = Request["curid"].ToInt();
            var cur = (curid == 0) ? c : CurrencyService.Single(x => x.ID == curid);
            
            ActMessage = cur.CurrencyName + "转出";
            return View(cur);
        }

        /// <summary>
        /// 提币列表
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult CurTransferOutList()
        {
            ActMessage = "提币列表";

            var c = CurrencyService.List(x => x.LineSwitch && !(x.IsCashCurrency ?? false)).Count() == 0 ? new JN.Data.Currency { ID = 0 } : CurrencyService.List(x => x.LineSwitch && !(x.IsCashCurrency ?? false)).OrderBy(x => x.ID).FirstOrDefault();//获取最后一条
            if (c.ID == 0) return Redirect("/app/home/index");
            int curid = Request["curid"].ToInt();
            var cur = (curid == 0) ? c : CurrencyService.Single(x => x.ID == curid);
            ViewBag.Currency = cur;

            return View();
        }
        /// <summary>
        /// 获取提币列表数据
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult getCurTransferOutList(int? page)
        {
            int pageSize = 10;
            int curid = Request["curid"].ToInt();

            var list = RaCoinService.List(x => x.UID == Umodel.ID && x.Direction == "out" && x.CurID == curid);
            int totalPage = (int)System.Math.Ceiling((double)list.Count() / pageSize);//总页数
            return Json(new { data = list.OrderByDescending(x => x.CreateTime).ThenByDescending(x => x.ID).ToPagedList(page ?? 1, pageSize), pages = totalPage }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 提币详情
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult CurTransferOutDetail(int id)
        {
            ActMessage = "提币详情";
            ViewBag.Title = ActMessage;
            var model = RaCoinService.ListInclude(x => x.OutTable_Currency).Where(x => x.ID == id && x.UID == Umodel.ID).FirstOrDefault();
            return View(model);
        }
        #endregion

        #region 申请及取消提币

        /// <summary>
        /// 人民币提币，异步 Name:Lin  Time:2017年7月18日14:25:51
        /// </summary>
        /// <param name="number"></param>
        /// <returns></returns>
        public ActionResult RMBCash()
        {
            var c = CurrencyService.List(x => x.LineSwitch && (x.IsCashCurrency ?? false)).Count() == 0 ? new JN.Data.Currency { ID = 0 } : CurrencyService.List(x => x.LineSwitch && (x.IsCashCurrency ?? false)).OrderBy(x => x.ID).FirstOrDefault();//获取最后一条

            if (c.ID == 0) return Redirect("/app/home/index");
            int curid = Request["curid"].ToInt();
            var cur = (curid == 0) ? c : CurrencyService.Single(x => x.ID == curid);

            ViewBag.Title = cur.CurrencyName + "提现";
            ActMessage = ViewBag.Title;
            ViewBag.Currency = cur;

            return View();
        }

        /// <summary>
        /// 人民币提币提交
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RMBCash(FormCollection form)
        {
            ViewBag.Title = "人民币提币提交";
            Result result = new Result();
            result = JN.Services.Manager.Finance.WithdrawCash(form, Umodel, CurrencyService);
            return Json(result);
        }
        /// <summary>
        /// 提现列表
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult RMBCashList()
        {
            ActMessage = "提现列表";
            ViewBag.Title = ActMessage;

            var c = CurrencyService.List(x => x.LineSwitch && (x.IsCashCurrency ?? false)).Count() == 0 ? new JN.Data.Currency { ID = 0 } : CurrencyService.List(x => x.LineSwitch &&(x.IsCashCurrency ?? false)).OrderBy(x => x.ID).FirstOrDefault();//获取最后一条
            if (c.ID == 0) return Redirect("/app/home/index");
            int curid = Request["curid"].ToInt();
            var cur = (curid == 0) ? c : CurrencyService.Single(x => x.ID == curid);
            ViewBag.Currency = cur;

            return View();
        }
        /// <summary>
        /// 获取提现列表数据
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult getRMBCashList(int? page)
        {
            int pageSize = 10;
            int curid = Request["curid"].ToInt();

            var list = TakeCashService.List(x => x.UID == Umodel.ID && x.CurID == curid);
            int totalPage = (int)System.Math.Ceiling((double)list.Count() / pageSize);//总页数
            return Json(new { data = list.OrderByDescending(x => x.CreateTime).ThenByDescending(x => x.ID).ToPagedList(page ?? 1, pageSize), pages = totalPage }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 提现详情
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult RMBCashDetail(int id)
        {
            ActMessage = "提现详情";
            ViewBag.Title = ActMessage;
            var model = TakeCashService.SingleAndInit(x => x.ID == id && x.UID == Umodel.ID);
            return View(model);
        }

        /// <summary>
        /// 取消提币
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult CancelTakeCash(int id)
        {
            ViewBag.Title = "取消提币";
            Result result = new Result();
            var model = TakeCashService.Single(id);
            if (model != null && model.UID == Umodel.ID)
            {
                using (System.Transactions.TransactionScope ts = new System.Transactions.TransactionScope())
                {
                    result = JN.Services.Manager.Finance.CancelTakeCash(id, TakeCashService);
                    if (result.Status == 200)
                    {
                        ts.Complete();
                    }
                }
            }
            else {
                result.Message = "非法操作";
            }

            return Json(result);
         
        }

        #endregion

        #region 转出提币币种

        /// <summary>
        /// 转出提币币种 Name：Lin  Time：2017年7月18日14:32:41
        /// </summary>
        /// <returns></returns>
        public ActionResult RaSend()
        {
            ActMessage = "转出提币币种";
            return View();
        }
        /// <summary>
        /// 转出xx币种 Name：Lin  Time：2017年7月18日14:32:41
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RaSend(FormCollection form)
        {
            ReturnResult result = new ReturnResult();
            try
            {
                if (CacheExtensions.CheckCache("RaSend" + Umodel.ID))//查找缓存是否存在
                {
                    throw new CustomException("正在处理数据,请耐心等待。");
                }
                CacheExtensions.SetCache("RaSend" + Umodel.ID, "", MvcCore.Extensions.CacheTimeType.ByMinutes, 10);//每1分钟   

                string amount = form["Amount"];
                string walletaddress = form["WalletAddress"];
                string tag = form["Tag"];
                string password2 = form["password2"];
                string curid = form["curid"];
                if (string.IsNullOrEmpty(curid)) throw new CustomException("对不起，参数接收失败！");

                int c = curid.ToInt();

JN.Web/Areas/APP/Views/CashTransfer/CurTransferOutDetail.cshtml
@model JN.Data.RaCoin
@{
    Layout = "~/Areas/App/Views/Shared/_Layout" + JN.Services.Tool.ConfigHelper.GetConfigString("Theme") + ".cshtml";
    ViewBag.Title = "提币详情";

    JN.Data.User Umodel = MvcCore.Unity.Get<JN.Data.Service.IUserService>().Single(JN.Services.UserLoginHelper.CurrentUser().ID);
}

<link href="/Theme/app/css/trade.css" rel="stylesheet">
<header class="header">
    <div class="header-return mui-action-back">
        @*<a href="javascript:history.go(-1);"></a>*@
    </div>

    <div class="logo">@T(ViewBag.Title)</div>
</header>

<section class="container">
    <div class="trade-people">
        <div class="trade-people-photo">
            <img src="@(Umodel.HeadFace ?? "/Theme/app/images/member.png") ">
        </div>

        <div class="trade-people-name">
            <h3>@(Umodel.UserName)@(!string.IsNullOrWhiteSpace(Umodel.RealName) ? "(" + Umodel.RealName + ")" : "")</h3>
        </div>
    </div>
    <div class="clr"></div>

    <div class="trade-order-details">
        <ul>
            <li>
                <label>@T("时间")</label>
                <span>@Model.CreateTime.ToString("yyyy-MM-dd HH:mm:ss")</span>
            </li>

            <li>
                <label>@T("提现数量")</label>
                <span class="order-details-price">@Model.DrawMoney.ToDouble()</span>
            </li>

            <li>
                <label>@T("币种")</label>
                <span class="order-details-status">@T(Model.OutTable_Currency.CurrencyName)</span>
            </li>

            <li>
                <label>@T("手续费")</label>
                <span>@Model.Poundage.ToDouble()</span>
            </li>

            <li>
                <label>@T("实收金额")</label>
                <span>@Model.ActualDrawMoney.ToDouble()</span>
            </li>

            <li>
                <label>@T("钱包地址")</label>
                <span>@Model.WalletAddress</span>
            </li>

            <li>
                <label>@T("状态")</label>
                <span>@T(typeof(JN.Data.Enum.TakeCaseStatus).GetEnumDesc(Model.Status))</span>
            </li>
        </ul>
    </div>
</section>

JN.Web/Areas/APP/Views/CashTransfer/CurTransferOutList.cshtml
@{
    JN.Data.Currency cur = ViewBag.Currency as JN.Data.Currency;
    string curl = Request.Url.ToString().ToLower();
    int curid = cur.ID;
    Layout = "~/Areas/App/Views/Shared/_Layout" + JN.Services.Tool.ConfigHelper.GetConfigString("Theme") + ".cshtml";
}

<header class="header">
    <div class="header-return mui-action-back">
        @*<a href="javascript:history.go(-1);"></a>*@
    </div>
    <div class="logo">@T(cur.CurrencyName)@T("提币记录")</div>
</header>
<section class="container">
    <div class="record-table">
        <table>
            <thead>
                <tr>
                    <th>@T("时间")</th>
                    <th>@T("提现金额")</th>
                    <th>@T("手续费")</th>
                    <th>@T("状态")</th>
                </tr>
            </thead>

            <tbody id="listcontainer"></tbody>
        </table>
    </div>
</section>

<script src="~/Plugin/layer/layui/layui.js"></script><!--layui插件js-->
<link href="~/Plugin/layer/layui/css/layui.css" rel="stylesheet" />
<script>
    layui.use('flow', function () {
        //var $ = layui.jquery; //不用额外加载jQuery，flow模块本身是有依赖jQuery的，直接用即可。
        var flow = layui.flow;
        flow.load({
            elem: '#listcontainer', //指定列表容器
            isAuto: false,//是否自动加载
            done: function (page, next) { //到达临界点（默认滚动触发），触发下一页
                var lis = [];
                //以jQuery的Ajax请求为例，请求下一页数据（注意：page是从2开始返回）
                $.get('@Url.Action("getCurTransferOutList")?page=' + page + "&curid=@(curid)", function (res) {
                    var strhtml = "";
                    //假设你的列表返回在data集合中
                    layui.each(res.data, function (index, item) {
                        strhtml += '<tr  onclick="goDetail('+ item.ID +')">';
                        strhtml += '<td>' + ChangeDateFormat(item.CreateTime) + '</td>';
                        strhtml += '<td>' + item.DrawMoney + '</td>';
                        strhtml += '<td>' + item.Poundage + '</td>';
                        strhtml += '<td><span class="record-num">' + (item.Status == 1 ? "@T("审核锁定")" : item.Status == 2 ? "@T("已支付")": item.Status == 3 ? "@T("已完成")" : item.Status == 0 ? "@T("待审核")" : "@T("已取消")") + '</span></td>';
                        strhtml += '</tr>';
                    });
                    lis.push(strhtml);
                    //alert(lis);
                    //执行下一页渲染，第二参数为：满足“加载更多”的条件，即后面仍有分页
                    //pages为Ajax返回的总页数，只有当前页小于总页数的情况下，才会继续出现加载更多
                    next(lis.join(''), page < res.pages);
                });
            }
        });
    });
    //日期格式转换
    function ChangeDateFormat(jsondate) {
        jsondate = jsondate.replace("/Date(", "").replace(")/", "");
        if (jsondate.indexOf("+") > 0) {
            jsondate = jsondate.substring(0, jsondate.indexOf("+"));
        }
        else if (jsondate.indexOf("-") > 0) {
            jsondate = jsondate.substring(0, jsondate.indexOf("-"));
        }

        var date = new Date(parseInt(jsondate, 10));
        var month = date.getMonth() + 1 < 10 ? "0" + (date.getMonth() + 1) : date.getMonth() + 1;
        var currentDate = date.getDate() < 10 ? "0" + date.getDate() : date.getDate();
        var currentHours = date.getHours() < 10 ? "0" + date.getHours() : date.getHours();
        var currentMinutes = date.getMinutes() < 10 ? "0" + date.getMinutes() : date.getMinutes();
        return month
            + "-"
            + currentDate
            + ""
            + " "
            + currentHours
            + ":"
            + currentMinutes;
    }
    function goDetail(id) {
        window.location.href = "@Url.Action("CurTransferOutDetail")?id="+id;
    }
</script>
<script type="text/javascript">
    //弹窗取消提示
    function Cancel(id) {
        layer.confirm("@T("您确定要取消这条记录么？")", {
            title: "@T("取消确认")", //标题
            btn: ['@T("确定")', '@T("取消")']  //按钮
    },
    function (index) {
        layer.close(index);
     $.post("@(Url.Action("CancelSendRa"))", { id: id }, function (data) {
                if (data.Status == 200) {
                    layer.msg("@T("操作成功!")", { icon: 1 }, function () {
                        location.reload();
                    });
                } else {
                    layer.msg(data.Message, { icon: 2 });
                }
            });
    });
    };
</script>

JN.Web/Areas/APP/Views/CashTransfer/CurTransferout.cshtml
@model JN.Data.Currency
@{
    //ViewBag.Title = "转入";
    JN.Data.User Umodel = null;
    if (JN.Services.UserLoginHelper.CurrentUser() == null)
    {
        Response.Redirect(Url.Action("Index", "Login"));
    }
    else
    {
        Umodel = MvcCore.Unity.Get<JN.Data.Service.IUserService>().Single(JN.Services.UserLoginHelper.CurrentUser().ID);
    }

    Layout = "~/Areas/APP/Views/Shared/_Layout18080102.cshtml";

    decimal money = JN.Services.Manager.Users.WalletCur((int)Model.WalletCurID, Umodel);

    var curList = MvcCore.Unity.Get<JN.Data.Service.ICurrencyService>().List(x => x.LineSwitch && x.IsCashTransfer).ToList();
}
<link href="/Theme/App/css/base.css" rel="stylesheet">


<header class="header">
    <div class="header-return mui-action-back">
        @*<a href="@Url.Action("index", "home")"></a>*@
    </div>

    <div class="logo">@T(ViewBag.Title)</div>

    <div class="header-btn muiopen">
        <a href="@Url.Action("CurTransferOutList", "CashTransfer")?curid=@Model.ID">@T("提现记录")</a>
    </div>
</header>
@*<div style="margin-top:50px;">
        <a>离线</a>/
        <a>现金</a>
    </div>*@
<section class="container">
    @*<div class="tab-title">
        <div class="tab-item">
            <div class="lava"></div>
            @foreach (var item in curList)
            {
                <a href="@((item.IsCashCurrency ?? false) ? Url.Action("RMBCash", "CashTransfer"): Url.Action("CurTransferOut", "CashTransfer"))?curid=@item.ID" class="@(item.ID == Model.ID ? "active":"")">@T(item.CurrencyName)</a>
            }     
        </div>
    </div>*@

    <div class="tab-content">
        <div class="form-widget">
            <form action="" id="frmEdit" method="post">
                <div class="form-box">
                    <div class="clr-small"></div>
                    <div class="form-group">
                        <label class="form-label fontcolor alignright">@T("转出数量")</label>

                        <div class="form-control">
                            <input placeholder="@T("可转出数量")@money.ToString("F4")" name="amount" class="primary-input">

                            @*<span class="trade-all">全部</span>*@
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="form-label fontcolor topalign alignright">@T("接受地址")</label>

                        <div class="form-control padding">
                            @*<input name="address" value="">*@
                            <textarea class="textareasize"></textarea>
                        </div>

                    </div>
                    @if (Model.NetworkType == (int)JN.Data.Enum.CurrencyNetworkType.Ripple || Model.NetworkType == (int)JN.Data.Enum.CurrencyNetworkType.EOS)
                    {
                        <div class="form-group">
                            <label class="form-label">@T("标签(tag)<br>备注(memo)")</label>

                            <div class="form-control">
                                <textarea class="fs12 bgtransp" id="textarea" rows="5" name="Tag" placeholder="@T("请输入标签或备注")"></textarea>
                            </div>
                        </div>
                    }

                    <div class="form-group">
                        <label class="form-label fontcolorn alignright">@T("交易密码")</label>

                        <div class="form-control">
                            <input type="password" name="password2" placeholder="@T("请输入交易密码")">
                        </div>
                    </div>
                </div>

                <div class="form-submit">
                    <button type="button" id="btnEdit" class="form-submit-btn">@T("确认转出")</button>
                </div>
                <input type="hidden" name="curid" value="@Model.ID"/>
            </form>
        </div>
    </div>

</section>
<script src="~/Plugin/Jquery/jquery.form.js"></script>
<script type="text/javascript">
    $("#btnEdit").click(function () {
        $('#btnEdit').attr("disabled", "disabled");
        $("#frmEdit").ajaxSubmit({
            url: "@Url.Action("RaSend")",
            type: "post",
            success: function (data) {
                if (data.Status == 200) {
                       layer.msg("@T("提交成功，请您等待审核")", { icon: 1 }, function () {
                            location.href = "@Url.Action("CurTransferOutList", "CashTransfer")?curid=@Model.ID";
                        });
                } else {
                layer.msg(data.Message, { icon: 2 });
                    $('#btnEdit').removeAttr("disabled");
                }
            },
            error: function (error) {
                layer.msg(error, { icon: 2 });
                $('#btnEdit').removeAttr("disabled");
            }
        });
    });
</script>

JN.Web/Areas/APP/Views/CashTransfer/RMBCash.cshtml
@{
    ViewBag.Title = "转入";
    JN.Data.User Umodel = null;
    if (JN.Services.UserLoginHelper.CurrentUser() == null)
    {
        Response.Redirect(Url.Action("Index", "Login"));
    }
    else
    {
        Umodel = MvcCore.Unity.Get<JN.Data.Service.IUserService>().Single(JN.Services.UserLoginHelper.CurrentUser().ID);
    }
    Layout = "~/Areas/App/Views/Shared/_Layout" + JN.Services.Tool.ConfigHelper.GetConfigString("Theme") + ".cshtml";

    JN.Data.Currency cur = ViewBag.Currency as JN.Data.Currency;

    //账户余额
    decimal balance = JN.Services.Manager.Users.WalletCur((int)cur.WalletCurID, Umodel);

    var curList = MvcCore.Unity.Get<JN.Data.Service.ICurrencyService>().List(x => x.LineSwitch && x.IsCashTransfer).ToList();
}
<link href="/Theme/App/css/base.css" rel="stylesheet">


<header class="header">
    <div class="header-return">
        <a href="@Url.Action("index", "home")"></a>
    </div>
    <div class="logo">@T("现金提现")</div>

    <div class="header-btn">
        <a href="@Url.Action("RMBCashList", "CashTransfer")?curid=@cur.ID">@T("提现记录")</a>
    </div>
</header>

<section class="container tab-container">
    <div class="tab-title">
        <div class="tab-item">
            <div class="lava" style="left:50%;"></div>
            @foreach (var item in curList)
            {
                <a href="@((item.IsCashCurrency ?? false) ? Url.Action("RMBCash", "CashTransfer"): Url.Action("CurTransferOut", "CashTransfer"))?curid=@item.ID" class="@(item.ID == cur.ID ? "active":"")">@T(item.CurrencyName)</a>
            }    
        </div>
    </div>

    <div class="tab-content">
        <div class="form-widget">
            <form action="" id="frmEdit" method="post">
                <div class="form-box">
                    <div class="form-group">
                        <label class="form-label">@T("转出数量")</label>

                        <div class="form-control">
                            <input placeholder="@T("可转出数量")@balance.ToString("F2")" name="drawmoney" id="drawmoney" class="primary-input">

                            @*<span class="trade-all">全部</span>*@
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="form-label">@T("到账金额")</label>

                        <div class="form-control">
                            <input value="0.0000" id="actualMoney" readonly="readonly">
                        </div>

                        <div id="ChooseUnit" class="choose-unit">
                            <span>@T("选择银行卡")</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="form-label">@T("交易密码")</label>

                        <div class="form-control">
                            <input type="password" name="password2" placeholder="@T("请输入交易密码")">
                        </div>
                    </div>
                </div>

                <div class="form-submit">
                    <input type="hidden" id="rate" value="@(cur.TbPoundage ?? 0)"><!--手续费-->
                    <input name="curid" value="@cur.ID" type="hidden" /><!--ID-->
                    <button type="button" id="btnEdit" class="form-submit-btn">@T("确认转出")</button>
                </div>
                <!--弹框-->
                <div class="popup">
                    <div class="popup-box">
                        <div class="popup-box-title">@T("选择银行")</div>

                        <div class="popup-box-content">
                            <div class="choose-list">
                                <ul>
                                    @{
                                        var bankList = MvcCore.Unity.Get<JN.Data.Service.IUserBankCardService>().List(x => x.UID == Umodel.ID).OrderByDescending(x => x.IsDefault).ToList();
                                        if (bankList.Any())
                                        {
                                            foreach (var item in bankList)
                                            {
                                                <li>
                                                    <input type="radio" name="bankid" value="@item.ID">
                                                    <label>@(item.BankName + item.BankCard)</label>
                                                </li>
                                            }
                                        }
                                    }
                                </ul>
                            </div>
                        </div>

                        <div class="popup-submit">
                            <button class="cancle-btn" type="button">@T("取消")</button>
                            <button type="button" class="confirm-btn">@T("确认")</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>




<script src="~/Plugin/Jquery/jquery.form.js"></script>
<script type="text/javascript">
    //提现提交
    $("#btnEdit").click(function () {
        $('#btnEdit').attr("disabled", "disabled");
        $("#frmEdit").ajaxSubmit({
            url: "@Url.Action("RMBCash")",
            type: "post",
            success: function (data) {
                if (data.Status == 200) {
                    layer.msg("@(T("申请成功，请耐心等待系统审核"))!", { icon: 1 },function(){
                        location.href = "@Url.Action("RMBCashList", "CashTransfer")?curid=@cur.ID"; 
                    })
                } else {
                    layer.msg("@T("申请失败：")" + data.Message, { icon: 2 });
                    $('#btnEdit').removeAttr("disabled");
                }
            },
            error: function (error) {
                layer.msg(error, { icon: 2 });
                $('#btnEdit').removeAttr("disabled");
            }
        });
    });

    //选择银行卡
    $('#ChooseUnit').click(function () {
        $('.popup').fadeIn();

        var h = ($(window).height() - $('.popup-box').height()) / 2;
        $('.popup-box').css('margin-top', h);
    });

    //取消选择
    $('.cancle-btn').click(function () {
        $('.popup').fadeOut();
    });

    $("#drawmoney").keyup(function () {
        $("#actualMoney").val(Math.round(parseFloat($("#drawmoney").val()) * (1-parseFloat($("#rate").val())) * 100) / 100);
    })
</script>