JN.Web/Areas/AdminCenter/Controllers/MallManagementController.cs
using JN.Data.Service;
using JN.Services.Manager;
using JN.Services.Tool;
using MvcCore.Controls;
using System;
using System.Collections;
using System.Web;
using System.Web.Mvc;
using System.Linq;
using PagedList;
using System.Collections.Generic;
using System.Data.SqlClient;

namespace JN.Web.Areas.AdminCenter.Controllers
{
    public class MallManagementController : BaseController
    {
        private readonly ISysDBTool SysDBTool;
        private readonly IShop_Product_CategoryService Shop_Product_CategoryService;
        private readonly IUserService UserService;
        private readonly IShop_ProductService Shop_ProductService;
        private readonly IShop_FloorService Shop_FloorService;
        private readonly IShop_CommentsService Shop_CommentsService;
        private readonly IShop_Tmp_Pro_ImgService Shop_Tmp_Pro_ImgService;
        private readonly IShop_Order_DetailsService Shop_Order_DetailsService;
        private readonly IShop_Home_GroupService Shop_Home_GroupService;
        private readonly IShop_SPECService Shop_SPECService;
        private readonly IShop_Product_SKUService Shop_Product_SKUService;


        public MallManagementController(ISysDBTool SysDBTool,
            IShop_Product_CategoryService Shop_Product_CategoryService,
            IUserService UserService,
            IShop_ProductService Shop_ProductService,
            IShop_FloorService Shop_FloorService,
            IShop_CommentsService Shop_CommentsService,
            IShop_Tmp_Pro_ImgService Shop_Tmp_Pro_ImgService,
            IShop_Order_DetailsService Shop_Order_DetailsService,
            IShop_Home_GroupService Shop_Home_GroupService,
            IShop_SPECService Shop_SPECService,
            IShop_Product_SKUService Shop_Product_SKUService
            )
        {
            this.UserService = UserService;
            this.SysDBTool = SysDBTool;
            this.Shop_Product_CategoryService = Shop_Product_CategoryService;
            this.Shop_ProductService = Shop_ProductService;
            this.Shop_FloorService = Shop_FloorService;
            this.Shop_CommentsService = Shop_CommentsService;
            this.Shop_Tmp_Pro_ImgService = Shop_Tmp_Pro_ImgService;
            this.Shop_Order_DetailsService = Shop_Order_DetailsService;
            this.Shop_Home_GroupService = Shop_Home_GroupService;
            this.Shop_SPECService = Shop_SPECService;
            this.Shop_Product_SKUService = Shop_Product_SKUService;
        }

        #region
        public ActionResult HomeTitle(int? page)
        {
            return View();
        }
        #endregion 

        #region 商品分类
        /// <summary>
        /// 商品分类管理
        /// </summary>
        /// <returns></returns>
        public ActionResult ProductCategory(int? page)
        {
            ActMessage = "商品分类";
            //var list = Shop_Product_CategoryService.List().WhereDynamic(FormatQueryString(HttpUtility.ParseQueryString(Request.Url.Query))).OrderByDescending(x => x.Id).ToList();

            var allCategory = Shop_Product_CategoryService.List().ToList();
            //List<JN.Data.Shop_Product_Category> allCategory = new List<Data.Shop_Product_Category>();
            if (allCategory.Count() == 0)
            {
                return View(allCategory.ToPagedList(page ?? 1, 20));
            }

            List<JN.Data.Shop_Product_Category> categoryList = new List<Data.Shop_Product_Category>();

            //1.先找最顶层
            var vfirstCategory = allCategory.Where(x => x.ParentId == 0);
            if (vfirstCategory.Count() > 0)
            {
                var firstCategory = vfirstCategory.ToList();
                for (int i = 0; i < firstCategory.Count(); i++)
                {
                    categoryList.Add(firstCategory[i]);
                    //2.找第二层
                    var vSecondCategory = allCategory.Where(x => x.ParentId == firstCategory[i].Id);
                    if (vSecondCategory.Count() > 0)
                    {
                        var SecondCategory = vSecondCategory.ToList();
                        for (int j = 0; j < SecondCategory.Count(); j++)
                        {
                            categoryList.Add(SecondCategory[j]);
                            //3.找第三层
                            var vThiredCategory = allCategory.Where(x => x.ParentId == SecondCategory[j].Id);
                            if (vThiredCategory.Count() > 0)
                            {
                                var ThiredCategory = vThiredCategory.ToList();
                                for (int n = 0; n < ThiredCategory.Count(); n++)
                                {
                                    categoryList.Add(ThiredCategory[n]);
                                }
                            }
                        }
                    }
                }
            }

            return View(categoryList.ToPagedList(page ?? 1, 20));
        }

        #region 分类编辑

        /// <summary>
        /// 分类编辑
        /// </summary>
        /// <param name="fc"></param>
        /// <returns></returns>
        public ActionResult ModifyCategory(int? id)
        {
            ActMessage = "修改分类";
            ViewBag.Title = ActMessage;
            return View(Shop_Product_CategoryService.Single(id));

        }
        [HttpPost]
        public ActionResult ModifyCategory(FormCollection fc)
        {
            ReturnResult result = new ReturnResult();
            try
            {
                var entity = Shop_Product_CategoryService.SingleAndInit(fc["id"].ToInt());
                string name = fc["name"];
                string color = fc["color"];
                string cateImg = fc["cateImg"];
                string sort = fc["sort"];

                if (string.IsNullOrEmpty(entity.Name)) throw new Exception("分类名称不能为空！");
                if (Shop_Product_CategoryService.List(x => x.Name == name.Trim()).Count() > 0 && entity.Name != name) throw new Exception("分类名称已被使用！");

                if (string.IsNullOrEmpty(sort)) throw new Exception("分类排序不能为空！");
                if (!StringHelp.IsNumber(sort)) throw new Exception("请输入正确的分类排序！");
                #region 父级分类
                string cateid = fc["cateid"];
                int cId;
                int.TryParse(cateid, out cId);
                var model = Shop_Product_CategoryService.Single(x => x.Id == cId);
                if (model != null)
                {
                    string[] pPacth = model.Ppacth.Split(',');
                    if (pPacth.Length > 3 && entity.Id != cateid.ToInt()) throw new Exception("请选择该项的上级分类！");//分类最多三层，修改时根据路径判断是否选择前两层

                    entity.Ppacth = model.Ppacth + model.Id + ",";
                    entity.parentName = model.Name;
                }
                else
                {
                    entity.Ppacth = "0,";//选择顶级分类
                    entity.parentName = null;
                }
                entity.ParentId = cId;
                #endregion

                entity.Name = name;
                entity.Color = color;
                entity.CateImg = cateImg;
                entity.Sort = sort.ToInt();
                Shop_Product_CategoryService.Update(entity);

                SysDBTool.Commit();
                result.Status = 200;

                //JN.Services.Manager.Category.SaveCategoryHtml(Shop_Product_CategoryService, JN.Services.Tool.ConfigHelper.GetConfigString("ShopTheme"));
                //this.SaveCategoryHtml();//生成分类HTML
            }
            catch (Exception ex)
            {
                result.Message = ex.Message;
                logs.WriteErrorLog(HttpContext.Request.Url.ToString(), ex);
            }
            return Json(result);

        }
        #endregion

        #region 生成分类HTML
        ///// <summary>
        ///// 生成分类HTML
        ///// </summary>
        //public void SaveCategoryHtml()
        //{
        //    string str = "";

        //    int a = 0;
        //    var vProCategory = Shop_Product_CategoryService.List();
        //    //var vProCategory = MvcCore.Unity.Get<JN.Data.Service.IShop_Product_CategoryService>().List(x => x.ParentId == 0);

        //    if (vProCategory != null)
        //    {
        //        string strUrl = "/ShopCenter/QueryDataByCategory?cat=";
        //        foreach (Data.Shop_Product_Category cate in vProCategory.ToList())
        //        {
        //            if (a > 9)
        //            {
        //                break;
        //            }

        //            if (a % 2 > 0)
        //            {
        //                str += "<li class=\"mod_cate alt\">";
        //            }
        //            else
        //            {
        //                str += "<li class=\"mod_cate\">";
        //            }

        //            str += "<h2><i class=\"arrow_dot fr\"></i><a href=\"" + strUrl + cate.Id + "\">" + cate.Name + "</a></h2>";

        //            //str += "<p class=\"mod_cate_r\"><a href=\"" + strUrl + cate.Id"\">黄豆</a><a href="#">绿豆</a><a href="#">芸豆</a><a href="#">蚕豆</a><a href="#">荞麦</a></p>";

        //            str += "<div class=\"mod_subcate\">";
        //            str += "<div class=\"mod_subcate_main\" style=\"width:100%\">";
        //            str += "<dl>";

        //            str += "<dt>" + cate.Name + "</dt>";
        //            str += "<dd>";

        //            int id = cate.Id;
        //            var vChildList = Shop_Product_CategoryService.List(x => x.ParentId == id); //SandMem.BLL.ProductCategory.SelectList("ParentId=" + cate.Id);
        //            //var vChildList = vProCategory.Where(x => x.ParentId == id);
        //            if (vChildList != null)
        //            {
        //                foreach (Data.Shop_Product_Category childcate in vChildList.ToList())
        //                {

JN.Web/Areas/AdminCenter/Views/MallManagement/AddHomeGroup.cshtml
@model JN.Data.Shop_Home_Group
@{
    Layout = "~/Areas/AdminCenter/Views/Shared/_Layout.cshtml";
}


<div id="content">
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")" class="glyphicons home"><i></i> 首页</a></li>
        <li class="divider"></li>
        <li>@ViewBag.Title</li>
    </ul>
    <div class="separator bottom"></div>
    <div class="innerLR">
        <div class="col-xs-12">
            @using (Ajax.BeginForm("AddHomeGroup", new { }, new AjaxOptions() { HttpMethod = "Post", OnSuccess = "afterPost" }, new { id = "saveForm", @class = "form-horizontal" }))
            {
                <div class="control-group">
                    <input type="hidden" id="id" name="id" value="@Model.Id" />
                    <label class="control-label">分组名称：</label>
                    <div class="controls">
                        <span class="input-icon">
                            <input type="text" name="Name" value="@Model.Name" />
                        </span>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">分组标题：</label>
                    <div class="controls">
                        <span class="input-icon">
                            <input type="text" name="Title" value="@Model.Title" />
                        </span>
                    </div>
                </div>
                <div class="controls">
                    <input id="submit" name="Submit" type="submit" class="btn" value="提 交" />
                </div>

            }
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Plugin/Jquery/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        //提交后返回结果
        function afterPost(data) {
            if (data.Status == 200) {
                alert("保存成功，即将为您跳转页面!");
                location.href = "@(Url.Action("HomeGroup", "MallManagement"))";
            } else {
                alert("保存失败！错误信息：" + data.Message);
            }
        }
    </script>
}

JN.Web/Areas/AdminCenter/Views/MallManagement/Comments.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<JN.Data.Shop_Comments>
@{
    ViewBag.Title = "评论列表";
    Layout = "~/Areas/AdminCenter/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")" class="glyphicons home"><i></i> 首页</a></li>
        <li class="divider"></li>
        <li>@ViewBag.Title</li>
    </ul>
    <div class="separator bottom"></div>
    <!--新闻搜索-->
    <div class="filter-bar margin-bottom-none">
        <form method="get">
            <div>
                <select name="datefiled" style="width: 80px;">
                    <option value="CreateTime" @(Request["datefiled"] == "CreateTime" ? "selected" : "")>创建时间</option>
                </select>
            </div>
            <div>
                <label>从:</label>
                <div class="input-append">
                    <input type="text" name="dateform" class="input-mini datepicker" value="@Request["dateform"]" style="width: 63px;" />
                    <span class="add-on glyphicons calendar"><i></i></span>
                </div>
            </div>
            <div>
                <label>到:</label>
                <div class="input-append">
                    <input type="text" name="dateto" class="input-mini datepicker" value="@Request["dateto"]" style="width: 63px;" />
                    <span class="add-on glyphicons calendar"><i></i></span>
                </div>
            </div>
            <div>
            </div>
            <div style="margin-left:10px">
                <select name="keyfiled" style="width: 80px;">
                    <option value="OrderNumber" @(Request["keyfiled"] == "OrderNumber" ? "selected" : "")>订单编号</option>
                    <option value="UserName" @(Request["keyfiled"] == "UserName" ? "selected" : "")>用户名</option>
                    <option value="pid" @(Request["keyfiled"] == "pid" ? "selected" : "")>商品名称</option>
                    @*<option value="sid" @(Request["keyfiled"] == "sid" ? "selected" : "")>店铺名称</option>*@
                    <option value="Content" @(Request["keyfiled"] == "Content" ? "selected" : "")>评论内容</option>
                </select>
            </div>
            <div>
                <div class="input-append">
                    <input type="text" name="keyword" class="input-mini" style="width: 150px;" value="@Request["keyword"]" placeholder="请输入查询关键词" />
                    <span style="margin: 0;" class="btn-action single glyphicons circle_question_mark" data-toggle="tooltip" data-placement="top" data-original-title="使用模糊查询可在关键字前后加上“%”"><i></i></span>
                </div>
            </div>
            <div>
                <div class="input-append">
                    <input type="submit" value="查询" />
                </div>
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
    <!--评论页面-->
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>订单编号</th>
                    <th>用户</th>
                    <th>商品</th>
                    @*<th>店铺</th>*@
                    <th>评论内容</th>
                    <th>商品评价</th>
                    <th>服务评价</th> 
                    <th>描述相符</th>
                    <th>卖家服务</th>
                    <th>物流服务</th>
                    <th>创建时间</th>
                    <th>显示</th>
                    
                </tr>
            </thead>
            <tbody>
                @if (Model.Count > 0)
                {
                    var pList = MvcCore.Unity.Get<JN.Data.Service.IShop_ProductService>().List().ToList();
                    var shopList = MvcCore.Unity.Get<JN.Data.Service.IShop_InfoService>().List().ToList();
                    var userList = MvcCore.Unity.Get<JN.Data.Service.IUserService>().List().ToList();
                    for (int i = 0; i < Model.Count; i++)
                    {
                        <tr>
                            <td>
                                @Model[i].OrderNumber
                            </td>
                            <td>
                                @Model[i].UserName
                            </td>
                            <td>
                               @* @(MvcCore.Unity.Get<JN.Data.Service.IShop_ProductService>().Single(Model[i].pid).ProductName)*@
                                @{
                                    var pName = pList.Where(x => x.Id == Model[i].pid).ToList();
                                    if (pName != null && pName.Count() > 0)
                                    {
                                        @pName.First().ProductName
                                    }
                                 }
                            </td>
                            @*<td>                             
                                @{
                                    var shopName = shopList.Where(x => x.ID == Model[i].sid).ToList();
                                    if (shopName != null && shopName.Count() > 0)
                                    {
                                        @shopName.First().ShopName
                                    }
                                }
                            </td>*@
                            <td>
                                @(Model[i].Content.ToString().Length > 60 ? Model[i].Content.ToString().Substring(0, 60) + "……" : Model[i].Content.ToString())
                            </td>
                            <td>
                                @(Model[i].proComment.ToString().Length > 60 ? Model[i].proComment.ToString().Substring(0, 60) + "……" : Model[i].proComment.ToString())
                            </td>
                            <td>
                                @(Model[i].shopComment.ToString().Length > 60 ? Model[i].shopComment.ToString().Substring(0, 60) + "……" : Model[i].shopComment.ToString())
                            </td>
                            <td>
                                @Model[i].proStar
                            </td>
                            <td>
                                @Model[i].shopStart
                            </td>
                            <td>
                                @Model[i].wlStart
                            </td>
                            <td>
                                @Model[i].CreateTime
                            </td>
                            <td>
                                <input type="checkbox" data-value="@Model[i].ID" onclick="ShowOrCloseComment(this)" @(Convert.ToBoolean(Model[i].IsLock) == false ? "checked" : "") />
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <div class="separator top form-inline small">
            @Html.PagedListPager((IPagedList)Model, page => Url.Action(ViewContext.RouteData.Values["action"].ToString(),
                       JN.Services.Tool.StringHelp.GetQueryString(HttpUtility.ParseQueryString(Request.Url.Query), page)), new PagedListRenderOptions() { ContainerDivClasses = new string[] { "pagination pagination-small pull-right" } })

        </div>
    </div>
</div>

@section scripts{

    <script type="text/javascript">
        //是否显示
        function ShowOrCloseComment(obj) {
            var id = $(obj).attr("data-value");
            $.post("@Url.Action("ShowOrCloseComment", "MallManagement")", { id: id }, function (data) {
                if (data.Status != 200) {
                    alert("操作失败！");
                }

            });
        }
    </script>
}

JN.Web/Areas/AdminCenter/Views/MallManagement/HomeGroup.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<JN.Data.Shop_Home_Group>
@{
    ViewBag.Title = "首页分组管理";
    Layout = "~/Areas/AdminCenter/Views/Shared/_Layout.cshtml";
}

<!-- Content -->
<div id="content">
    <!-- Breadcrumb -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")" class="glyphicons home"><i></i> 首页</a></li>
        <li class="divider"></li>
        <li>@ViewBag.Title</li>
    </ul>
    <div class="separator bottom"></div>
    <!-- // Breadcrumb END -->
    <div class="innerLR">
        <div class="tabbable">
            <div class="filter-bar margin-bottom-none">
                <form method="get" action="">
                    <div style="margin-left:10px">
                        <label>分组名称:</label>
                    </div>
                    <div>
                        <div class="input-append">
                            <input type="text" name="Name" class="input-mini" style="width: 150px;" placeholder="请输入查询关键词" />
                        </div>
                    </div>
                    <div>
                        <div class="input-append">
                            <input type="submit" value="查询" />
                        </div>
                    </div>
                    <div>
                        &nbsp;&nbsp;<a href="@Url.Action("AddHomeGroup")" class="btn btn-primary">添加分组</a>
                    </div>
                </form>
            </div>
            <div>
                <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                    <tr class="table02-title">
                        @*<th>编号</th>*@
                        <th>分组名称</th>
                        <th>分组标题</th>
                        <th>创建用户</th>
                        <th>创建时间</th>
                        <th>操作</th>
                    </tr>
                    @if (Model.Count > 0)
                    {
                        for (int i = 0; i < Model.Count; i++)
                        {
                            <tr>
                                @*<td class="center text-muted">
                                    @(i + 1)
                                </td>*@
                                <td>
                                    @Model[i].Name
                                </td>
                                <td>
                                    @Model[i].Title
                                </td>
                                <td>
                                    @Model[i].UserName
                                </td>
                                <td>
                                    @Model[i].CreateTime
                                </td>
                                <td>
                                    <a href="@Url.Action("AddHomeGroup", new {id = Model[i].Id })">编辑</a>
                                </td>
                            </tr>
                        }
                    }
                </table>
                <div class="separator top form-inline small">
                    @Html.PagedListPager((IPagedList)Model, page => Url.Action(ViewContext.RouteData.Values["action"].ToString(),
                       JN.Services.Tool.StringHelp.GetQueryString(HttpUtility.ParseQueryString(Request.Url.Query), page)), new PagedListRenderOptions() { ContainerDivClasses = new string[] { "pagination pagination-small pull-right" } })
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{

}

JN.Web/Areas/AdminCenter/Views/MallManagement/HomeTitle.cshtml
@{
    ViewBag.Title = "HomeTitle";
    Layout = "~/Areas/AdminCenter/Views/Shared/_Layout.cshtml";
}

<h2>HomeTitle</h2>

JN.Web/Areas/AdminCenter/Views/MallManagement/ModifyCategory.cshtml
@model JN.Data.Shop_Product_Category
@{

    Layout = "~/Areas/AdminCenter/Views/Shared/_Layout.cshtml";
    var list = MvcCore.Unity.Get<JN.Data.Service.IShop_Product_CategoryService>().List(x => x.ParentId == 0);
}

<div id="content" style="text-align: left">

    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")" class="glyphicons home"><i></i> 首页</a></li>
        <li class="divider"></li>
        <li>@ViewBag.Title</li>
    </ul>
    <div class="separator bottom"></div>

    @if (Model != null)
    {
        <div>
            @using (Ajax.BeginForm("ModifyCategory", new { }, new AjaxOptions() { HttpMethod = "Post", OnSuccess = "AfterEdit" }, new { id = "frmSet" }))
            {
                <table class="niunantab" style="margin-left:70px;">
                    <tr>
                        <td>所有分类</td>
                        <td>
                            <select name="cateid">
                                <option value="0">顶级分类</option>
                                @{
                                    if (list != null && list.Any())
                                    {
                                        foreach (var cate in list.ToList())
                                        {
                                            var childList = MvcCore.Unity.Get<JN.Data.Service.IShop_Product_CategoryService>().List(x => x.ParentId == cate.Id);//上级分类下的子类
                                            <option value="@cate.Id" @(Model != null && Model.ParentId == cate.Id ? "selected" : "")>@cate.Name</option>
                                            if (childList != null && childList.Count() > 0)
                                            {
                                                foreach(var childcate in childList.ToList())
                                                {
                                                    var childList2 = MvcCore.Unity.Get<JN.Data.Service.IShop_Product_CategoryService>().List(x => x.ParentId == childcate.Id);
                                                    <option value="@childcate.Id" @(Model != null && Model.ParentId == childcate.Id ? "selected" : "")>&nbsp;﹄@childcate.Name</option>
                                                    if(childList2 != null && childList2.Count() > 0)
                                                    {
                                                        foreach (var childcate2 in childList2.ToList())
                                                        {
                                                            <option value="@childcate2.Id" @(Model != null && Model.ParentId == childcate2.Id ? "selected" : "")>&nbsp;&nbsp;&nbsp;﹄@childcate2.Name</option>
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>分类名称</td>
                        <td><input type="text" name="name" value="@Model.Name" /></td>
                        <td><input type="hidden" name="id" value="@Model.Id" /></td>
                    </tr>
                    @*<tr>
                        <td>分类颜色</td>
                        <td><input type="text" name="color" value="@Model.Color" /></td>
                    </tr>*@
                    <tr>
                        <td>分类排序</td>
                        <td><input type="text" name="sort" value="@Model.Sort" onkeyup=""/></td>
                        <td><p>1、由于商城分类只有10行，所以需要显示的分类排序数字不要大于10</p>
                            <p>2、相同排序的顶层分类会并排显示在商城的分类菜单中</p>
                        </td>
                    </tr>
                    <tr>
                        <td>分类图片：</td>
                        <td>
                            <img style="width: 180px; height: 180px" id="MainPic" src="@Model.CateImg" />
                            <input type="button" id="btnUpManiPic" value="选择图片" class="" />
                            <input type="hidden" name="cateImg" id="hidMainimgSrc" value="" />
                        </td>
                    </tr>
                    <tr>
                        <td><input name="Submit" type="submit" class="btn" value="完  成" /></td>
                    </tr>
                </table>
            }
        </div>
    }
</div>
@section scripts{
    <link href="~/Plugin/kindeditor-4.1.9/themes/default/default.css" rel="stylesheet" />
    <link href="~/Plugin/kindeditor-4.1.9/plugins/code/prettify.css" rel="stylesheet" />

    <script src="~/Plugin/kindeditor-4.1.9/kindeditor.js"></script>
    <script src="~/Plugin/kindeditor-4.1.9/lang/zh_CN.js"></script>
    <link href="~/Plugin/kindeditor-4.1.9/plugins/code/prettify.css" rel="stylesheet" />
    <script src="~/Plugin/Jquery/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        //上传
        KindEditor.ready(function (K) {
            var editor = K.editor({
                uploadJson: '@(Url.Action("CateUpMainPic", "MallManagement"))?ASPSESSID=' + "@Session.SessionID",
                allowFileManager: true
            });
            K('#btnUpManiPic').click(function () {
                editor.loadPlugin('image', function () {
                    editor.plugin.imageDialog({
                        showRemote: false,
                        imageUrl: K('#UrlMainPic').val(),
                        clickFn: function (url, title, width, height, border, align) {
                            K('#MainPic').attr("src", url);
                            K('#hidMainimgSrc').val(url);
                            editor.hideDialog();
                        }
                    });
                });
            });
        });

        //显示主图
        //function ShowPic(data) {
        //    var url = data.SaveName;
        //    $("#imgSrc").val(url);
        //}
        //提交后返回结果
        function AfterEdit(data) {
            if (data.Status == 200) {
                alert("编辑成功！");
                location.href = "@(Url.Action("ProductCategory", "MallManagement"))";
            }
            else {
                alert("保存失败！错误信息：" + data.Message);
            }
        }
    </script>
}