JN.Web/Areas/APP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JN.Data.Service;
using JN.Services.Tool;
using System.Text;
using System.Data.Entity.SqlServer;
using JN.Services.Manager;
using JN.Data.Extensions;
using JN.Services.CustomException;
using System.Data.Entity.Validation;
using System.IO;

namespace JN.Web.Areas.APP.Controllers
{
 
    public class HomeController : BaseController
    {
        #region 初始化，构造函数
        private readonly IUserService UserService;
        private readonly ISysSettingService SysSettingService;
        private readonly ISysDBTool SysDBTool;
        private readonly IActLogService ActLogService;
        public HomeController(ISysDBTool SysDBTool, 
            IUserService UserService,
            ISysSettingService SysSettingService,
            IActLogService ActLogService)
        {
            this.UserService = UserService;
            this.SysSettingService = SysSettingService;
            this.SysDBTool = SysDBTool;
            this.ActLogService = ActLogService;
        }

        #endregion
        #region 网站首页，修改登录密码，交易密码，网站退出

        #region 网站首页
        /// <summary>
        /// 网站首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewBag.Title = "首页";
            ActMessage = ViewBag.Title;
            return View();
        }
        #endregion

        #region 视频
        public ActionResult Video()
        {
            ViewBag.Title = "视频";
            logs.WriteLog("视频");
            return View();
        }
        #endregion

        #region 安全退出


        //退出
        public ActionResult Logout()
        {
            ActMessage = "用户退出";
            Services.UserLoginHelper.UserLogout();
            return Redirect("/App/Login");
        }
        #endregion

        #region 修改一级密码

        /// <summary>
        /// 修改一级密码
        /// </summary>
        /// <returns></returns>
        public ActionResult ChangePassword()
        {
            ActMessage = "修改一级密码";
            ViewBag.Title = ActMessage;
            return View();
        }

        /// <summary>
        /// 修改登录密码提交
        /// </summary>
        /// <param name="form">表单</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ChangePassword(FormCollection form)
        {
            ActMessage = "修改登录密码提交";
            ViewBag.Title = ActMessage;
            ReturnResult result = new ReturnResult();
            try
            {
                string oldpassword = form["oldpassword"];
                string newpassword = form["newpassword"];
                string connewpassword = form["connewpassword"];
                // string password2 = form["password2"];
                if (oldpassword.Trim().Length == 0 || newpassword.Trim().Length == 0)
                    throw new CustomException("原登录密码、新登录密码不能为空");

                if (newpassword != connewpassword)
                    throw new CustomException("新登录密码与确认密码不相符");
                if (Umodel.Password != oldpassword.ToMD5().ToMD5())
                    throw new CustomException("原登录密码不正确");

                //if (Umodel.Password2 != password2.ToMD5().ToMD5())
                //    throw new CustomException("二级密码不正确");

                Umodel.Password = newpassword.ToMD5().ToMD5();
                UserService.Update(Umodel);
                SysDBTool.Commit();
                result.Status = 200;
            }
            catch (CustomException ex)
            {
                result.Message = ex.Message;
            }
            catch (Exception ex)
            {
                result.Message = "The network system is busy, please try again later!";
                logs.WriteErrorLog(HttpContext.Request.Url.ToString(), ex);
            }
            return Json(result);
        }
        #endregion

        #region 修改二级密码

        /// <summary>
        /// 修改二级密码
        /// </summary>
        /// <returns></returns>
        public ActionResult ChangePassword2()
        {
            ActMessage = "修改交易密码";
            return View();
        }


        /// <summary>
        /// 修改交易密码提交
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ChangePassword2(FormCollection form)
        {
            ActMessage = "修改交易密码提交";
            ReturnResult result = new ReturnResult();
            try
            {
                string oldpassword2 = form["oldpassword2"];
                string newpassword2 = form["newpassword2"];
                string connewpassword2 = form["connewpassword2"];
                string password = form["password"];
                if (oldpassword2.Trim().Length == 0 || newpassword2.Trim().Length == 0)
                    throw new CustomException("原交易密码、新交易密码不能为空");

                if (newpassword2 != connewpassword2)
                    throw new CustomException("新交易密码与确认密码不相符");

                if (Umodel.Password2 != oldpassword2.ToMD5().ToMD5())
                    throw new CustomException("原交易密码不正确");
                if (Umodel.Password != password.ToMD5().ToMD5())
                    throw new CustomException("登录密码不正确");
                Umodel.Password2 = newpassword2.ToMD5().ToMD5();
                UserService.Update(Umodel);
                SysDBTool.Commit();
                result.Status = 200;
            }
            catch (CustomException ex)
            {
                result.Message = ex.Message;
            }
            catch (Exception ex)
            {
                result.Message = "The network system is busy, please try again later!";
                logs.WriteErrorLog(HttpContext.Request.Url.ToString(), ex);
            }
            return Json(result);
        }
        #endregion
        #endregion
    } 
 



}

JN.Web/Areas/APP/Controllers/NoticeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JN.Data;
using JN.Data.Service;
using MvcCore.Controls;
using PagedList;

namespace JN.Web.Areas.APP.Controllers
{
    public class NoticeController : Controller
    {
        private readonly INoticeService NoticeService;
        private readonly ISysDBTool SysDBTool;
        private readonly IActLogService ActLogService;

        public NoticeController(ISysDBTool SysDBTool,
            INoticeService NoticeService,
            IActLogService ActLogService)
        {
            this.NoticeService = NoticeService;
            this.SysDBTool = SysDBTool;
            this.ActLogService = ActLogService;
        }

        //public ActionResult Index(int? page)
        //{
        //    ViewBag.Title = "公告列表";
        //    var list = NoticeService.List().OrderByDescending(x => x.ID);
        //    return View(list.ToPagedList(page ?? 1, 20));
        //}
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetNoticeList(int? page)
        {
            var list = NoticeService.List().OrderByDescending(x => x.ID);
            int pageSize = 10;
            var listdata = list.OrderByDescending(x => x.ID).ToPagedList(page ?? 1, pageSize);//取数据
            var countrow = list.Count();//取总条数
            int totalPage = (countrow + pageSize - 1) / pageSize;//取总页数
            return Json(new { data = listdata, pages = totalPage, count = listdata.Count() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Detail(int id)
        {

            ViewBag.Title = "公告详情";
            var model = NoticeService.Single(id);
            if (model != null)
                return View(model);
            else
            {
                ViewBag.ErrorMsg = "记录不存在或已被删除";
                return View("Error");
            }
        }
    }
}

JN.Web/Areas/AdminCenter/Controllers/HomeController.cs
using JN.Data.Service;
using JN.Services.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JN.Web.Areas.AdminCenter.Controllers
{
    public class HomeController : BaseController
    {
        private static List<Data.SysParam> cacheSysParam = MvcCore.Unity.Get<ISysParamService>().List(x => x.ID < 6000).ToList();

        //
        // GET: /AdminCenter/Index/
        public ActionResult Index()
        {
            //var userlist = MvcCore.Unity.Get<IUserService>().List(x => x.R3001 == null || x.R3001 == "").ToList();
            //foreach (var item in userlist)
            //{
            //    var r3001 = Users.GetRandomString(33, true, true, true, false, "1");
            //    item.R3001 = r3001;
            //    MvcCore.Unity.Get<IUserService>().Update(item);
            //    MvcCore.Unity.Get<ISysDBTool>().Commit();
            //}

            return View();
        }

        public ActionResult NoAuthority()
        {
            return View();
        }

        //退出
        public ActionResult Logout()
        {
            ActMessage = "退出系统";
            Services.AdminLoginHelper.AdminUserLogout();
            return Redirect(Url.Action("Index", "Login"));
        }

        public ActionResult ClearAllCache()
        {
            List<String> caches = MvcCore.Extensions.CacheExtensions.GetAllCache();
            foreach (var cachename in caches)
                MvcCore.Extensions.CacheExtensions.ClearCache(cachename);
            List<String> caches2 = Services.Tool.DataCache.GetAllCache();
            foreach (var cachename in caches2)
                Services.Tool.DataCache.ClearCache(cachename);
            Services.AdminLoginHelper.AdminUserLogout();
            Stocks.ClearAllTradeCache();//清币种缓存
            Stocks.HeavyLoad();//清币种参数缓存
            Bonus.HeavyLoad();//清参数缓存
            Finance.HeavyLoad();//清参数缓存
            Users.HeavyLoad();//清参数缓存
            Wallets.HeavyLoad();//清参数缓存
            return Redirect(Url.Action("Index", "Login"));
        }

        public ActionResult ChangePassword()
        {
            ActMessage = "修改密码";
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(FormCollection form)
        {
            string oldpassword = form["oldpassword"];
            string newpassword = form["newpassword"];
            string connewpassword = form["newpassword2"];
            string strErr = "";

            if (oldpassword.Trim().Length == 0 || newpassword.Trim().Length == 0)
                strErr += "原密码不能为空 <br />";

            if (newpassword != connewpassword)
                strErr += "新密码与确认密码不相符 <br />";


            if (Amodel.Password != oldpassword.ToMD5().ToMD5())
                strErr += "原密码不正确 <br />";
            if (strErr != "")
            {
                ViewBag.ErrorMsg = "抱歉您填写的信息有误： <br />" + strErr + "请核实后重新提交！";
                return View("Error");
            }

            Amodel.Password = newpassword.ToMD5().ToMD5();
            MvcCore.Unity.Get<IAdminUserService>().Update(Amodel);
            MvcCore.Unity.Get<ISysDBTool>().Commit();
            ActMessage = "密码修改成功";
            return View("Success");
        }
    }
}

JN.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace JN.Web.Controllers
{
    public class HomeController : Controller
    {
      
        public ActionResult Index()
        {           
            //设置语言版本
            string lang = Request["lang"];
            if (!string.IsNullOrEmpty(lang))
            {
                Services.Resource.ResourceProvider.Culture = lang;
            }
            ViewBag.Title = "网站首页";
            return Redirect("/AdminCenter/Login");
            //  return Redirect("/App/home");
            //return Redirect("/APP/Home/Video");
            //return View("Video");
        }
     

        public ActionResult Error()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            return View();
        }
    }
}

JN.Web/Areas/AdminCenter/Views/Home/ChangePassword.cshtml
@{
    Layout = "~/Areas/AdminCenter/Views/Shared/_Layout.cshtml";
}
<!-- Content -->
<div id="content">
    <!-- Breadcrumb -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")" class="glyphicons home"><i></i> 首页</a></li>
        <li class="divider"></li>
        <li>@ViewBag.Title</li>
    </ul>
    <div class="separator bottom"></div>
    <!-- // Breadcrumb END -->
    <div class="innerLR">
        <!-- PAGE CONTENT BEGINS -->

        <form class="form-horizontal" id="validation-form" method="post">
            <div class="control-group">
                <label class="control-label" for="adminname">原登录密码：</label>

                <div class="controls">
                    <div class="clearfix">
                        <input type="password" name="oldpassword" class="form-control" />
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="password">新登录密码：</label>

                <div class="controls">
                    <div class="clearfix">
                        <input type="password" name="newpassword" class="form-control" />
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="password">再次确认登录密码：</label>

                <div class="controls">
                    <div class="clearfix">
                        <input type="password" name="newpassword2" class="form-control" />
                    </div>
                </div>
            </div>

            <div class="hr hr-dotted"></div>
            <div class="control-group">
                <label class="control-label">&nbsp;</label>
                <div class="controls">
                    <button class="btn btn-primary" type="submit">
                        保 存
                    </button>
                </div>
            </div>
        </form>

        <!-- PAGE CONTENT ENDS -->
    </div><!-- /.col -->
</div><!-- /.row -->
@section scripts{
}
}

JN.Web/Areas/AdminCenter/Views/Home/Index.cshtml
@{
    ViewBag.Title = "管理首页";
    Layout = "~/Areas/AdminCenter/Views/Shared/_Layout.cshtml";
    var Amodel = JN.Services.AdminLoginHelper.CurrentAdmin();


}
<!-- page specific plugin styles -->
<!-- Content -->
<div id="content">
    <!-- Breadcrumb -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")" class="glyphicons home"><i></i> 首页</a></li>
        <li class="divider"></li>
        <li>@ViewBag.Title</li>
        <li class="pull-right" style="margin-top:5px">
            <a class="btn btn-primary" href="@(Url.Action("ClearAllCache"))">
                清除所有缓存
            </a>
        </li>
    </ul>
    <div class="separator bottom"></div>
    <!-- // Breadcrumb END -->
    <div class="innerLR">

        <div class="alert alert-primary">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>欢迎使用</strong> @(MvcCore.Unity.Get<JN.Data.Service.ISysSettingService>().Single(1).SysName)后台管理系统

        </div>
        <div class="separator bottom"></div>
        <div class="row-fluid">
            <div class="span2">

                <!-- Stats Widget -->
                <a href="" class="widget-stats margin-bottom-none">
                    <span class="glyphicons shopping_cart"><i></i></span>
                    <span class="txt">平台手续费</span>
                    <div class="clearfix"></div>
                    <span class="count label label-important">@(MvcCore.Unity.Get<JN.Data.Service.IUserService>().List().Count()>0?MvcCore.Unity.Get<JN.Data.Service.IUserService>().List().Sum(x=>x.Poundage??0):0)</span>
                </a>
                <!-- // Stats Widget END -->

            </div>
            

            <div class="span2">

                <!-- Stats Widget -->
                <a href="" class="widget-stats margin-bottom-none">
                    <span class="glyphicons user_add"><i></i></span>
                    <span class="txt">用户统计</span>
                    <div class="clearfix"></div>
                    <span class="count label label-warning">@(MvcCore.Unity.Get<JN.Data.Service.IUserService>().List().Count())</span>
                </a>
                <!-- // Stats Widget END -->

            </div>
            <div class="span2">

                <!-- Stats Widget -->
                <a href="/admincenter/Mail/Inbox" class="widget-stats margin-bottom-none">
                    <span class="glyphicons envelope"><i></i></span>
                    <span class="txt">未读留言</span>
                    <div class="clearfix"></div>
                    <span class="count label label-primary">@(MvcCore.Unity.Get<JN.Data.Service.IMessageService>().List(x => x.UID == 0 && x.IsRead == false && x.ToUID == 0).Count())</span>
                </a>
                <!-- // Stats Widget END -->

            </div>
          
        </div>
        <div class="separator bottom"></div>
        <div class="row-fluid">
            <div class="span6">

                <!-- Stats/List/Sparklines Widget -->
                <div class="widget" data-toggle="collapse-widget">

                    <!-- Widget Heading -->
                    <div class="widget-head">
                        <h4 class="heading glyphicons stats"><i></i>最新公告</h4>
                    </div>
                    <!-- // Widget Heading END -->

                    <div class="widget-body list collapse in">
                        <table class="table table-bordered table-condensed">

                            @*<!-- Table heading -->
            <thead>
                <tr>
                    <th class="center">No.</th>
                    <th>Column Heading</th>
                </tr>
            </thead>
            <!-- // Table heading END -->*@
                            <!-- Table body -->
                            <tbody>
                                @{
                                    var ggLst = MvcCore.Unity.Get<JN.Data.Service.INoticeService>().List().OrderByDescending(x => x.IsTop).ThenByDescending(x => x.ID).Take(10).ToList();
                                    if (ggLst.Count > 0)
                                    {

                                        foreach (var notice in ggLst)
                                        {
                                            <tr>
                                                <td class="center">@notice.CreateTime.ToString("yyyy-MM-dd")</td>
                                                <td>
                                                    <a href="@(Url.Action("Modify", "Notice", new { ID=notice.ID}))">
                                                        @notice.Title
                                                    </a>
                                                </td>
                                            </tr>
                                        }

                                    }
                                    else
                                    {
                                        <tr><td colspan="2">暂无通告</td></tr>
                                    }
                                }
                            </tbody>
                            <!-- // Table body END -->

                        </table> 
                    </div>
                </div>
                <!-- Stats/List/Sparklines Widget END -->

            </div>
            <div class="span6">

                <!-- Traffic Sources Pie Chart -->
                <div class="widget" data-toggle="collapse-widget">
                    <div class="widget-head">
                        <h4 class="heading glyphicons pie_chart"><i></i>登录历史</h4>
                    </div>
                    <div class="widget-body collapse in">
                        <table class="table table-bordered table-condensed">
                            @{
                                var actLst = MvcCore.Unity.Get<JN.Data.Service.IActLogService>().List(x => x.Location.Contains("/AdminCenter/Login") && x.UID == Amodel.ID).Take(10).OrderByDescending(x => x.ID).ToList();
                                if (actLst.Count > 0)
                                {

                                    foreach (var log in actLst)
                                    {
                                        <tr>
                                            <td>@log.IP</td>
                                            <td>@log.ActContent</td>
                                            <td>@log.CreateTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
                                        </tr>
                                    }

                                }
                            }
                        </table>

                   </div>
                </div>
                <!-- // Traffic Sources Pie Chart END -->

            </div>
        </div>
    </div>
    </div><!-- /.page-content -->
    <!-- page specific plugin scripts -->
    <!--[if lte IE 8]>
    <![endif]-->
    @section scripts{
        <script type="text/javascript">
            jQuery(function ($) {
                $('.widget-container-span').sortable({
                    connectWith: '.widget-container-span',
                    items: '> .widget-box',
                    opacity: 0.8,
                    revert: true,
                    forceHelperSize: true,
                    placeholder: 'widget-placeholder',
                    forcePlaceholderSize: true,
                    tolerance: 'pointer'
                });
            });
        </script>
    }

JN.Web/Areas/AdminCenter/Views/Home/NoAuthority.cshtml
@{
    ViewBag.Title = "您没有访问此页面的权限";
    Layout = "~/Areas/AdminCenter/Views/Shared/_Layout.cshtml";
}
<!-- page specific plugin styles -->
<!-- Content -->
<div id="content">
    <!-- Breadcrumb -->
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")" class="glyphicons home"><i></i> 首页</a></li>
        <li class="divider"></li>
        <li>@ViewBag.Title</li>
        <li class=" pull-right" style="margin-top:5px">
            <a class="btn btn-primary" href="@(Url.Action("ClearAllCache"))">
                清除所有缓存
            </a>
        </li>
    </ul>
    <div class="separator bottom"></div>
    <!-- // Breadcrumb END -->
    <div class="innerLR">
        <div class="alert alert-primary">
            <strong>提示:</strong><br>
            提示：您没有访问此页面的权限.
        </div>
    </div><!-- /.col -->
</div><!-- /.row -->
@section scripts{
}